<template>
  <div class="OnlineLength">
    <multi-level-table-component :activeName="activeName" :tabCtntList="tabCtntList" class="zone-check-multilevel"></multi-level-table-component>
  </div>
</template>

<style src="./reportRouter.css" type="text/css">
  
</style>

<script>
  import MultiLevelTableComponent from '@/components/MultiLevelTableComponent/MultiLevelTableComponent'
  export default {
    name: 'OnlineLength',
    components: {
      MultiLevelTableComponent,
    },
    data() {
      return {
        activeName: 'report_onlinelength_org_table',
        tabCtntList: {
          firCtnt: {
            tabLabel: '运管机构汇总',
            tabName: 'report_onlinelength_org_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }],
            tabHeader: [{
              headerKey: 'OrgName',
              headerVal: '运管机构',
              subHeaders: []
            }, {
              headerKey: 'total',
              headerVal: '合计',
              subHeaders: []
            }, {
              headerKey: 'First',
              headerVal: '1号',
              subHeaders: []
            }, {
              headerKey: 'Second',
              headerVal: '2号',
              subHeaders: []
            }, {
              headerKey: 'Third',
              headerVal: '3号',
              subHeaders: []
            }, {
              headerKey: 'Forth',
              headerVal: '4号',
              subHeaders: []
            }, {
              headerKey: 'Fifth',
              headerVal: '5号',
              subHeaders: []
            }, {
              headerKey: 'Sixth',
              headerVal: '6号',
              subHeaders: []
            }, {
              headerKey: 'Seventh',
              headerVal: '7号',
              subHeaders: []
            }, {
              headerKey: 'Eighth',
              headerVal: '8号',
              subHeaders: []
            }, {
              headerKey: 'Nineth',
              headerVal: '9号',
              subHeaders: []
            }, {
              headerKey: 'Tenth',
              headerVal: '10号',
              subHeaders: []
            }, {
              headerKey: 'Eleventh',
              headerVal: '11号',
              subHeaders: []
            }, {
              headerKey: 'Twelfth',
              headerVal: '12号',
              subHeaders: []
            }, {
              headerKey: 'Thirteenth',
              headerVal: '13号',
              subHeaders: []
            }, {
              headerKey: 'Fourteenth',
              headerVal: '14号',
              subHeaders: []
            }, {
              headerKey: 'Fifteenth',
              headerVal: '15号',
              subHeaders: []
            }, {
              headerKey: 'Sixteenth',
              headerVal: '16号',
              subHeaders: []
            }, {
              headerKey: 'Seventeenth',
              headerVal: '17号',
              subHeaders: []
            }, {
              headerKey: 'Eighteenth',
              headerVal: '18号',
              subHeaders: []
            }, {
              headerKey: 'Nineteenth',
              headerVal: '19号',
              subHeaders: []
            }, {
              headerKey: 'Twentith',
              headerVal: '20号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-First',
              headerVal: '21号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Second',
              headerVal: '22号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Third',
              headerVal: '23号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fourth',
              headerVal: '24号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fifth',
              headerVal: '25号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Sixth',
              headerVal: '26号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Seventh',
              headerVal: '27号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Eighth',
              headerVal: '28号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Nineth',
              headerVal: '29号',
              subHeaders: []
            }, {
              headerKey: 'Thirty',
              headerVal: '30号',
              subHeaders: []
            }, {
              headerKey: 'Thirty-First',
              headerVal: '31号',
              subHeaders: []
            }],
            TabCtnt: [{
              OrgName: '2016-05-03',
              total: '王小虎',
              First: '上海'
            }, {
              OrgName: '2016-05-03',
              total: '王小虎',
              First: '上海'
            }]
          },
          secCtnt: {
            tabLabel: '用户汇总',
            tabName: 'report_onlinelength_user_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            }, {
              searchType: 'input',
              labelName: '用户:',
              compVal: ''
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }],
            tabHeader: [{
              headerKey: 'UserName',
              headerVal: '用户',
              subHeaders: []
            }, {
              headerKey: 'OrgName',
              headerVal: '运管机构',
              subHeaders: []
            }, {
              headerKey: 'total',
              headerVal: '合计',
              subHeaders: []
            }, {
              headerKey: 'First',
              headerVal: '1号',
              subHeaders: []
            }, {
              headerKey: 'Second',
              headerVal: '2号',
              subHeaders: []
            }, {
              headerKey: 'Third',
              headerVal: '3号',
              subHeaders: []
            }, {
              headerKey: 'Forth',
              headerVal: '4号',
              subHeaders: []
            }, {
              headerKey: 'Fifth',
              headerVal: '5号',
              subHeaders: []
            }, {
              headerKey: 'Sixth',
              headerVal: '6号',
              subHeaders: []
            }, {
              headerKey: 'Seventh',
              headerVal: '7号',
              subHeaders: []
            }, {
              headerKey: 'Eighth',
              headerVal: '8号',
              subHeaders: []
            }, {
              headerKey: 'Nineth',
              headerVal: '9号',
              subHeaders: []
            }, {
              headerKey: 'Tenth',
              headerVal: '10号',
              subHeaders: []
            }, {
              headerKey: 'Eleventh',
              headerVal: '11号',
              subHeaders: []
            }, {
              headerKey: 'Twelfth',
              headerVal: '12号',
              subHeaders: []
            }, {
              headerKey: 'Thirteenth',
              headerVal: '13号',
              subHeaders: []
            }, {
              headerKey: 'Fourteenth',
              headerVal: '14号',
              subHeaders: []
            }, {
              headerKey: 'Fifteenth',
              headerVal: '15号',
              subHeaders: []
            }, {
              headerKey: 'Sixteenth',
              headerVal: '16号',
              subHeaders: []
            }, {
              headerKey: 'Seventeenth',
              headerVal: '17号',
              subHeaders: []
            }, {
              headerKey: 'Eighteenth',
              headerVal: '18号',
              subHeaders: []
            }, {
              headerKey: 'Nineteenth',
              headerVal: '19号',
              subHeaders: []
            }, {
              headerKey: 'Twentith',
              headerVal: '20号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-First',
              headerVal: '21号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Second',
              headerVal: '22号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Third',
              headerVal: '23号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fourth',
              headerVal: '24号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fifth',
              headerVal: '25号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Sixth',
              headerVal: '26号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Seventh',
              headerVal: '27号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Eighth',
              headerVal: '28号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Nineth',
              headerVal: '29号',
              subHeaders: []
            }, {
              headerKey: 'Thirty',
              headerVal: '30号',
              subHeaders: []
            }, {
              headerKey: 'Thirty-First',
              headerVal: '31号',
              subHeaders: []
            }],
            TabCtnt: [{
              UserName: '2016-05-03',
              OrgName: 'TYPE1',
              total: '王小虎',
              First: '上海'
            }, {
              UserName: '2016-05-03',
              OrgName: 'TYPE1',
              total: '王小虎',
              First: '上海'
            }]
          },
          trdCtnt: {
            tabLabel: '在线时长明细表',
            tabName: 'report_onlinelength_detailed_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            }, {
              searchType: 'input',
              labelName: '用户:',
              compVal: ''
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }],
            tabHeader: [{
              headerKey: 'OrgName',
              headerVal: '运管机构',
              subHeaders: []
            }, {
              headerKey: 'UserName',
              headerVal: '用户',
              subHeaders: []
            }, {
              headerKey: 'BDate',
              headerVal: '上线时间',
              subHeaders: []
            }, {
              headerKey: 'EDate',
              headerVal: '下线时间',
              subHeaders: []
            }, {
              headerKey: 'OnlineTime',
              headerVal: '在线时长',
              subHeaders: []
            }],
            TabCtnt: [{
              OrgName: '2016-05-03',
              UserName: 'TYPE1',
              BDate: '王小虎',
              EDate: '上海'
            }, {
              OrgName: '2016-05-03',
              UserName: 'TYPE1',
              BDate: '王小虎',
              EDate: '上海'
            }]
          },
          frthCtnt: {
            tabLabel: '当前用户在线情况',
            tabName: 'report_onlinelength_loginstatus_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            },{
              searchType: 'input',
              labelName: '用户:',
              compVal: ''
            }, {
              searchType: 'select',
              labelName: '登录状态:',
              compVal: '',
              options: [{
                value: '-1',
                label: '全部',
              }, {
                value: '1',
                label: '在线',
              }, {
                value: '0',
                label: '不在线',
              }],
            }],
            tabHeader: [{
              headerKey: 'UnitName',
              headerVal: '运管机构',
              subHeaders: []
            }, {
              headerKey: 'LoginCode',
              headerVal: '用户',
              subHeaders: []
            }, {
              headerKey: 'LoginDate',
              headerVal: '上线时间',
              subHeaders: []
            }, {
              headerKey: 'LoginStatus',
              headerVal: '当前登录状态',
              subHeaders: []
            }],
            TabCtnt: [{
              UnitName: '2016-05-03',
              LoginCode: 'TYPE1',
              LoginDate: '王小虎',
              LoginStatus: '上海'
            }, {
              UnitName: '2016-05-03',
              LoginCode: 'TYPE1',
              LoginDate: '王小虎',
              LoginStatus: '上海'
            }]
          }
        }
      }
    }
  }
</script>
