<template>
  <div class="CompanyCheckRank">
    <multi-level-table-component :activeName="activeName" :tabCtntList="tabCtntList" class="zone-check-multilevel"></multi-level-table-component>
    <p class="check-footer-p">
      注：1、仅针对两客一危进行统计；总分能按升序、降序排列，默认按降序排列；
    </p>
  </div>
</template>

<style src="./reportRouter.css" type="text/css">
  
</style>

<script>
  import MultiLevelTableComponent from '@/components/MultiLevelTableComponent/MultiLevelTableComponent'
  export default {
    name: 'CompanyCheckRank',
    components: {
      MultiLevelTableComponent,
    },
    data() {
      return {
        activeName: 'report_vehicleonline_zone_table',
        tabCtntList: {
          firCtnt: {
            tabLabel: '地区汇总',
            tabName: 'report_vehicleonline_zone_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            }, {
              searchType: 'input',
              labelName: '接入平台:',
              compVal: ''
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }, {
              searchType: 'treeCheckbox',
              labelName: '车辆类型:',
              compVal: '',
              treeOps: [{
                id: '1',
                label: '所有车辆',
                children: [{
                  id: '1-1',
                  label: '重点营运车辆',
                  children: [{
                    id: '1-1-1',
                    label: '两客一危'
                  }, {
                    id: '1-1-2',
                    label: '重货车辆'
                  }]
                }, {
                  id: '1-2',
                  label: '非重点营运车辆',
                  children: [{
                    id: '1-2-1',
                    label: '普通货运'
                  }, {
                    id: '1-2-2',
                    label: '农村客运'
                  }, {
                    id: '1-2-3',
                    label: '驾培车'
                  }, {
                    id: '1-2-4',
                    label: '出租车'
                  }, {
                    id: '1-2-5',
                    label: '公交车'
                  }, {
                    id: '1-2-6',
                    label: '租赁客车'
                  }, {
                    id: '1-2-7',
                    label: '校园车辆'
                  }, {
                    id: '1-2-8',
                    label: '其他车'
                  }]
                }]
              }],
              treeChkboxProps: {
                label: 'label',
                chidlren: 'children'
              }
            }],
            tabHeader: [{
              headerKey: 'ZoneName',
              headerVal: '地区',
              subHeaders: []
            }, {
              headerKey: 'total',
              headerVal: '月在线率',
              subHeaders: []
            }, {
              headerKey: 'LinkRelativeRatio',
              headerVal: '环比增长率',
              subHeaders: []
            }, {
              headerKey: 'First',
              headerVal: '1号',
              subHeaders: []
            }, {
              headerKey: 'Second',
              headerVal: '2号',
              subHeaders: []
            }, {
              headerKey: 'Third',
              headerVal: '3号',
              subHeaders: []
            }, {
              headerKey: 'Forth',
              headerVal: '4号',
              subHeaders: []
            }, {
              headerKey: 'Fifth',
              headerVal: '5号',
              subHeaders: []
            }, {
              headerKey: 'Sixth',
              headerVal: '6号',
              subHeaders: []
            }, {
              headerKey: 'Seventh',
              headerVal: '7号',
              subHeaders: []
            }, {
              headerKey: 'Eighth',
              headerVal: '8号',
              subHeaders: []
            }, {
              headerKey: 'Nineth',
              headerVal: '9号',
              subHeaders: []
            }, {
              headerKey: 'Tenth',
              headerVal: '10号',
              subHeaders: []
            }, {
              headerKey: 'Eleventh',
              headerVal: '11号',
              subHeaders: []
            }, {
              headerKey: 'Twelfth',
              headerVal: '12号',
              subHeaders: []
            }, {
              headerKey: 'Thirteenth',
              headerVal: '13号',
              subHeaders: []
            }, {
              headerKey: 'Fourteenth',
              headerVal: '14号',
              subHeaders: []
            }, {
              headerKey: 'Fifteenth',
              headerVal: '15号',
              subHeaders: []
            }, {
              headerKey: 'Sixteenth',
              headerVal: '16号',
              subHeaders: []
            }, {
              headerKey: 'Seventeenth',
              headerVal: '17号',
              subHeaders: []
            }, {
              headerKey: 'Eighteenth',
              headerVal: '18号',
              subHeaders: []
            }, {
              headerKey: 'Nineteenth',
              headerVal: '19号',
              subHeaders: []
            }, {
              headerKey: 'Twentith',
              headerVal: '20号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-First',
              headerVal: '21号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Second',
              headerVal: '22号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Third',
              headerVal: '23号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fourth',
              headerVal: '24号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fifth',
              headerVal: '25号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Sixth',
              headerVal: '26号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Seventh',
              headerVal: '27号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Eighth',
              headerVal: '28号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Nineth',
              headerVal: '29号',
              subHeaders: []
            }, {
              headerKey: 'Thirty',
              headerVal: '30号',
              subHeaders: []
            }, {
              headerKey: 'Thirty-First',
              headerVal: '31号',
              subHeaders: []
            }],
            TabCtnt: [{
              ZoneName: '2016-05-03',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }, {
              ZoneName: '2016-05-03',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }]
          },
          secCtnt: {
            tabLabel: '接入平台汇总',
            tabName: 'report_vehicleonline_platform_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            }, {
              searchType: 'input',
              labelName: '接入平台:',
              compVal: ''
            }, {
              searchType: 'select',
              labelName: '平台类型',
              compVal: '',
              options: [{
                value: '0',
                label: '全部',
              }, {
                value: '2',
                label: '两客一危平台',
              }, {
                value: '3',
                label: '货运平台',
              }, {
                value: '1',
                label: '其他平台',
              }],
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }, {
              searchType: 'treeCheckbox',
              labelName: '车辆类型:',
              compVal: '',
              treeOps: [{
                id: '1',
                label: '所有车辆',
                children: [{
                  id: '1-1',
                  label: '重点营运车辆',
                  children: [{
                    id: '1-1-1',
                    label: '两客一危'
                  }, {
                    id: '1-1-2',
                    label: '重货车辆'
                  }]
                }, {
                  id: '1-2',
                  label: '非重点营运车辆',
                  children: [{
                    id: '1-2-1',
                    label: '普通货运'
                  }, {
                    id: '1-2-2',
                    label: '农村客运'
                  }, {
                    id: '1-2-3',
                    label: '驾培车'
                  }, {
                    id: '1-2-4',
                    label: '出租车'
                  }, {
                    id: '1-2-5',
                    label: '公交车'
                  }, {
                    id: '1-2-6',
                    label: '租赁客车'
                  }, {
                    id: '1-2-7',
                    label: '校园车辆'
                  }, {
                    id: '1-2-8',
                    label: '其他车'
                  }]
                }]
              }],
              treeChkboxProps: {
                label: 'label',
                chidlren: 'children'
              }
            }],
            tabHeader: [{
              headerKey: 'ZoneName',
              headerVal: '接入平台',
              subHeaders: []
            }, {
              headerKey: 'TYPE',
              headerVal: '平台类型',
              subHeaders: []
            }, {
              headerKey: 'total',
              headerVal: '月在线率',
              subHeaders: []
            }, {
              headerKey: 'LinkRelativeRatio',
              headerVal: '环比增长率',
              subHeaders: []
            }, {
              headerKey: 'First',
              headerVal: '1号',
              subHeaders: []
            }, {
              headerKey: 'Second',
              headerVal: '2号',
              subHeaders: []
            }, {
              headerKey: 'Third',
              headerVal: '3号',
              subHeaders: []
            }, {
              headerKey: 'Forth',
              headerVal: '4号',
              subHeaders: []
            }, {
              headerKey: 'Fifth',
              headerVal: '5号',
              subHeaders: []
            }, {
              headerKey: 'Sixth',
              headerVal: '6号',
              subHeaders: []
            }, {
              headerKey: 'Seventh',
              headerVal: '7号',
              subHeaders: []
            }, {
              headerKey: 'Eighth',
              headerVal: '8号',
              subHeaders: []
            }, {
              headerKey: 'Nineth',
              headerVal: '9号',
              subHeaders: []
            }, {
              headerKey: 'Tenth',
              headerVal: '10号',
              subHeaders: []
            }, {
              headerKey: 'Eleventh',
              headerVal: '11号',
              subHeaders: []
            }, {
              headerKey: 'Twelfth',
              headerVal: '12号',
              subHeaders: []
            }, {
              headerKey: 'Thirteenth',
              headerVal: '13号',
              subHeaders: []
            }, {
              headerKey: 'Fourteenth',
              headerVal: '14号',
              subHeaders: []
            }, {
              headerKey: 'Fifteenth',
              headerVal: '15号',
              subHeaders: []
            }, {
              headerKey: 'Sixteenth',
              headerVal: '16号',
              subHeaders: []
            }, {
              headerKey: 'Seventeenth',
              headerVal: '17号',
              subHeaders: []
            }, {
              headerKey: 'Eighteenth',
              headerVal: '18号',
              subHeaders: []
            }, {
              headerKey: 'Nineteenth',
              headerVal: '19号',
              subHeaders: []
            }, {
              headerKey: 'Twentith',
              headerVal: '20号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-First',
              headerVal: '21号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Second',
              headerVal: '22号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Third',
              headerVal: '23号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fourth',
              headerVal: '24号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fifth',
              headerVal: '25号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Sixth',
              headerVal: '26号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Seventh',
              headerVal: '27号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Eighth',
              headerVal: '28号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Nineth',
              headerVal: '29号',
              subHeaders: []
            }, {
              headerKey: 'Thirty',
              headerVal: '30号',
              subHeaders: []
            }, {
              headerKey: 'Thirty-First',
              headerVal: '31号',
              subHeaders: []
            }],
            TabCtnt: [{
              ZoneName: '2016-05-03',
              TYPE: 'TYPE1',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }, {
              ZoneName: '2016-05-03',
              TYPE: 'TYPE2',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }]
          },
          trdCtnt: {
            tabLabel: '企业汇总',
            tabName: 'report_vehicleonline_company_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            }, {
              searchType: 'input',
              labelName: '运输企业:',
              compVal: ''
            }, {
              searchType: 'input',
              labelName: '接入平台:',
              compVal: ''
            }, {
              searchType: 'select',
              labelName: '平台类型',
              compVal: '',
              options: [{
                value: '0',
                label: '全部',
              }, {
                value: '2',
                label: '两客一危平台',
              }, {
                value: '3',
                label: '货运平台',
              }, {
                value: '1',
                label: '其他平台',
              }],
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }, {
              searchType: 'treeCheckbox',
              labelName: '车辆类型:',
              compVal: '',
              treeOps: [{
                id: '1',
                label: '所有车辆',
                children: [{
                  id: '1-1',
                  label: '重点营运车辆',
                  children: [{
                    id: '1-1-1',
                    label: '两客一危'
                  }, {
                    id: '1-1-2',
                    label: '重货车辆'
                  }]
                }, {
                  id: '1-2',
                  label: '非重点营运车辆',
                  children: [{
                    id: '1-2-1',
                    label: '普通货运'
                  }, {
                    id: '1-2-2',
                    label: '农村客运'
                  }, {
                    id: '1-2-3',
                    label: '驾培车'
                  }, {
                    id: '1-2-4',
                    label: '出租车'
                  }, {
                    id: '1-2-5',
                    label: '公交车'
                  }, {
                    id: '1-2-6',
                    label: '租赁客车'
                  }, {
                    id: '1-2-7',
                    label: '校园车辆'
                  }, {
                    id: '1-2-8',
                    label: '其他车'
                  }]
                }]
              }],
              treeChkboxProps: {
                label: 'label',
                chidlren: 'children'
              }
            }],
            tabHeader: [{
              headerKey: 'ZNAME',
              headerVal: '企业所属地区',
              subHeaders: []
            }, {
              headerKey: 'UnitName',
              headerVal: '企业名称',
              subHeaders: []
            }, {
              headerKey: 'TYPE',
              headerVal: '平台类型',
              subHeaders: []
            }, {
              headerKey: 'total',
              headerVal: '月在线率',
              subHeaders: []
            }, {
              headerKey: 'LinkRelativeRatio',
              headerVal: '环比增长率',
              subHeaders: []
            }, {
              headerKey: 'First',
              headerVal: '1号',
              subHeaders: []
            }, {
              headerKey: 'Second',
              headerVal: '2号',
              subHeaders: []
            }, {
              headerKey: 'Third',
              headerVal: '3号',
              subHeaders: []
            }, {
              headerKey: 'Forth',
              headerVal: '4号',
              subHeaders: []
            }, {
              headerKey: 'Fifth',
              headerVal: '5号',
              subHeaders: []
            }, {
              headerKey: 'Sixth',
              headerVal: '6号',
              subHeaders: []
            }, {
              headerKey: 'Seventh',
              headerVal: '7号',
              subHeaders: []
            }, {
              headerKey: 'Eighth',
              headerVal: '8号',
              subHeaders: []
            }, {
              headerKey: 'Nineth',
              headerVal: '9号',
              subHeaders: []
            }, {
              headerKey: 'Tenth',
              headerVal: '10号',
              subHeaders: []
            }, {
              headerKey: 'Eleventh',
              headerVal: '11号',
              subHeaders: []
            }, {
              headerKey: 'Twelfth',
              headerVal: '12号',
              subHeaders: []
            }, {
              headerKey: 'Thirteenth',
              headerVal: '13号',
              subHeaders: []
            }, {
              headerKey: 'Fourteenth',
              headerVal: '14号',
              subHeaders: []
            }, {
              headerKey: 'Fifteenth',
              headerVal: '15号',
              subHeaders: []
            }, {
              headerKey: 'Sixteenth',
              headerVal: '16号',
              subHeaders: []
            }, {
              headerKey: 'Seventeenth',
              headerVal: '17号',
              subHeaders: []
            }, {
              headerKey: 'Eighteenth',
              headerVal: '18号',
              subHeaders: []
            }, {
              headerKey: 'Nineteenth',
              headerVal: '19号',
              subHeaders: []
            }, {
              headerKey: 'Twentith',
              headerVal: '20号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-First',
              headerVal: '21号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Second',
              headerVal: '22号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Third',
              headerVal: '23号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fourth',
              headerVal: '24号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fifth',
              headerVal: '25号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Sixth',
              headerVal: '26号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Seventh',
              headerVal: '27号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Eighth',
              headerVal: '28号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Nineth',
              headerVal: '29号',
              subHeaders: []
            }, {
              headerKey: 'Thirty',
              headerVal: '30号',
              subHeaders: []
            }, {
              headerKey: 'Thirty-First',
              headerVal: '31号',
              subHeaders: []
            }],
            TabCtnt: [{
              ZNAME: '2016-05-03',
              UnitName: 'TYPE1',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }, {
              ZNAME: '2016-05-03',
              UnitName: 'TYPE1',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }]
          },
          frthCtnt: {
            tabLabel: '车辆汇总',
            tabName: 'report_vehicleonline_vehicle_table',
            tabCount: 0,
            btnEvents: [{
              iconName: 'el-icon-search',
              btnName: '查询'
            }, {
              iconName: 'el-icon-download',
              btnName: '导出数据'
            }],
            searchCreteria: [{
              searchType: 'input',
              labelName: '车牌号:',
              compVal: ''
            }, {
              searchType: 'input',
              labelName: '所属地区:',
              compVal: '湖南省'
            },{
              searchType: 'input',
              labelName: '接入平台:',
              compVal: ''
            },  {
              searchType: 'input',
              labelName: '运输企业:',
              compVal: ''
            }, {
              searchType: 'datePicker',
              labelName: '',
              compVal: ''
            }, {
              searchType: 'treeCheckbox',
              labelName: '车辆类型:',
              compVal: '',
              treeOps: [{
                id: '1',
                label: '所有车辆',
                children: [{
                  id: '1-1',
                  label: '重点营运车辆',
                  children: [{
                    id: '1-1-1',
                    label: '两客一危'
                  }, {
                    id: '1-1-2',
                    label: '重货车辆'
                  }]
                }, {
                  id: '1-2',
                  label: '非重点营运车辆',
                  children: [{
                    id: '1-2-1',
                    label: '普通货运'
                  }, {
                    id: '1-2-2',
                    label: '农村客运'
                  }, {
                    id: '1-2-3',
                    label: '驾培车'
                  }, {
                    id: '1-2-4',
                    label: '出租车'
                  }, {
                    id: '1-2-5',
                    label: '公交车'
                  }, {
                    id: '1-2-6',
                    label: '租赁客车'
                  }, {
                    id: '1-2-7',
                    label: '校园车辆'
                  }, {
                    id: '1-2-8',
                    label: '其他车'
                  }]
                }]
              }],
              treeChkboxProps: {
                label: 'label',
                chidlren: 'children'
              }
            }],
            tabHeader: [{
              headerKey: 'LicensePlat',
              headerVal: '车牌号',
              subHeaders: []
            }, {
              headerKey: 'PlateColor',
              headerVal: '车牌颜色',
              subHeaders: []
            }, {
              headerKey: 'total',
              headerVal: '月在线率',
              subHeaders: []
            }, {
              headerKey: 'LinkRelativeRatio',
              headerVal: '环比增长率',
              subHeaders: []
            }, {
              headerKey: 'ZName',
              headerVal: '企业所属地区',
              subHeaders: []
            }, {
              headerKey: 'CityName',
              headerVal: '企业所属市(州)',
              subHeaders: []
            }, {
              headerKey: 'CompanyName',
              headerVal: '企业名称',
              subHeaders: []
            }, {
              headerKey: 'VehicleType',
              headerVal: '车辆类型',
              subHeaders: []
            }, {
              headerKey: 'PlatformName',
              headerVal: '接入平台',
              subHeaders: []
            }, {
              headerKey: 'First',
              headerVal: '1号',
              subHeaders: []
            }, {
              headerKey: 'Second',
              headerVal: '2号',
              subHeaders: []
            }, {
              headerKey: 'Third',
              headerVal: '3号',
              subHeaders: []
            }, {
              headerKey: 'Forth',
              headerVal: '4号',
              subHeaders: []
            }, {
              headerKey: 'Fifth',
              headerVal: '5号',
              subHeaders: []
            }, {
              headerKey: 'Sixth',
              headerVal: '6号',
              subHeaders: []
            }, {
              headerKey: 'Seventh',
              headerVal: '7号',
              subHeaders: []
            }, {
              headerKey: 'Eighth',
              headerVal: '8号',
              subHeaders: []
            }, {
              headerKey: 'Nineth',
              headerVal: '9号',
              subHeaders: []
            }, {
              headerKey: 'Tenth',
              headerVal: '10号',
              subHeaders: []
            }, {
              headerKey: 'Eleventh',
              headerVal: '11号',
              subHeaders: []
            }, {
              headerKey: 'Twelfth',
              headerVal: '12号',
              subHeaders: []
            }, {
              headerKey: 'Thirteenth',
              headerVal: '13号',
              subHeaders: []
            }, {
              headerKey: 'Fourteenth',
              headerVal: '14号',
              subHeaders: []
            }, {
              headerKey: 'Fifteenth',
              headerVal: '15号',
              subHeaders: []
            }, {
              headerKey: 'Sixteenth',
              headerVal: '16号',
              subHeaders: []
            }, {
              headerKey: 'Seventeenth',
              headerVal: '17号',
              subHeaders: []
            }, {
              headerKey: 'Eighteenth',
              headerVal: '18号',
              subHeaders: []
            }, {
              headerKey: 'Nineteenth',
              headerVal: '19号',
              subHeaders: []
            }, {
              headerKey: 'Twentith',
              headerVal: '20号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-First',
              headerVal: '21号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Second',
              headerVal: '22号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Third',
              headerVal: '23号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fourth',
              headerVal: '24号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Fifth',
              headerVal: '25号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Sixth',
              headerVal: '26号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Seventh',
              headerVal: '27号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Eighth',
              headerVal: '28号',
              subHeaders: []
            }, {
              headerKey: 'Twenty-Nineth',
              headerVal: '29号',
              subHeaders: []
            }, {
              headerKey: 'Thirty',
              headerVal: '30号',
              subHeaders: []
            }, {
              headerKey: 'Thirty-First',
              headerVal: '31号',
              subHeaders: []
            }],
            TabCtnt: [{
              LicensePlat: '2016-05-03',
              PlateColor: 'TYPE1',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }, {
              LicensePlat: '2016-05-03',
              PlateColor: 'TYPE1',
              total: '王小虎',
              LinkRelativeRatio: '上海'
            }]
          }
        }
      }
    }
  }
</script>
